FROM public.ecr.aws/lambda/provided:al2023

COPY clara-native-lambda /var/runtime/bootstrap
COPY aws-lambda-rie /usr/local/bin/aws-lambda-rie
ENTRYPOINT ["/lambda-entrypoint.sh", "clara_native_lambda.Handler"]
